"""empty message

Revision ID: 7a838abcb59a
Revises: None
Create Date: 2016-04-27 00:29:26.511013

"""

# revision identifiers, used by Alembic.
revision = '7a838abcb59a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('auther', sa.Unicode(length=255), nullable=True),
    sa.Column('publisher', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Unicode(length=255), nullable=True),
    sa.Column('book_title', sa.Unicode(length=255), nullable=True),
    sa.Column('impression', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['book_title'], ['books.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diaries')
    op.drop_table('books')
    ### end Alembic commands ###
